name: Rust Release Build

on:
  push:
    tags:
      - '[A-Z]*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './target -> release'

      - name: Build Release
        run: |
          IFS='.' read -ra parts <<< "${{ github.ref_name }}"
          cargo run --release "${parts[0]}" "${parts[1]}" "${parts[2]}" "${parts[3]}"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Upload Lflist Conf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lflist.conf
          asset_name: lflist.conf
          asset_content_type: text/plain